import Head from "next/head";
import Card from "@/components/card.jsx";
import Project from "@/components/projects.jsx";

import Socials from '@/components/socials.jsx';
import ActivitiesCard from '@/components/activities.jsx'; // all 3 of these don't need {} because default export funciton
import Calculator from '@/components/calculator.jsx'

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillVideoCamera,
  AiFillAlert,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import React, { Suspense, useState } from 'react';


import av from "../public/av.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import resume from "../public/resume.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
import web9 from "../public/web9.png";
import web10 from "../public/web10.png";
import web11 from "../public/web11.png";



import { data } from "autoprefixer";

const LazyCalculator = React.lazy(() => import('@/components/calculator.jsx')); // dynamic loading utilizing react's lazy()  loading to avoid rendering the second the website is 
const LazyGame = React.lazy(() => import('@/components/game.jsx'));
const socials = [
  {

    href: "https://test.com",
    sourcey: AiFillTwitterCircle
  },
  {
    href: "https://test.com",
    sourcey: AiFillLinkedin
  },
  {
    href: "https://test.com",
    sourcey: AiFillYoutube
  },
  {
    href: "https://test.com",
    sourcey: AiFillAlert
  }


]
const portfolioInfo = [
  {
    description: "My first JS game",
    sourcey: web7 // right image path
  },
  {
    description: "My first introduction to local storage",
    sourcey: web8 // right image path
  },
  {
    description: "My first JS Quiz",
    sourcey: web9 // right image path
  },
  {
    description: "GPA calculator project",
    sourcey: web10 // right image path
  },
  {
    description: "A currency converter with local storage",
    sourcey: web11 // right image path
  },

]
const cardInfo = [
  {
    title: "All My Code",
    description: "Proident mollit amet aliquip dolor consequat commodo fugiat aliquip laborum adipisicing cillum occaecat eiusmod.",
    children: (<>
      <h4 className="py-4 text-teal-600">Tools I use</h4>
      <p className="text-gray-800 py-1">Github</p>
      <p className="text-gray-800 py-1">Vscode</p>
    </>)
  },
  {
    title: "All My Code",
    description: "Proident mollit amet aliquip dolor consequat commodo fugiat aliquip laborum adipisicing cillum occaecat eiusmod.",
    children: (<>
      <h4 className="py-4 text-teal-600">Tools I use</h4>
      <p className="text-gray-800 py-1">Github</p>
      <p className="text-gray-800 py-1">Vscode</p>
    </>)
  },
  {
    title: "All My Code",
    description: "Proident mollit amet aliquip dolor consequat commodo fugiat aliquip laborum adipisicing cillum occaecat eiusmod.",
    children: (<>
      <h4 className="py-4 text-teal-600">Tools I use</h4>
      <p className="text-gray-800 py-1">Github</p>
      <p className="text-gray-800 py-1">Vscode</p>
    </>)
  },
  {
    title: "All My Code",
    description: "Proident mollit amet aliquip dolor consequat commodo fugiat aliquip laborum adipisicing cillum occaecat eiusmod.",
    children: (<>
      <h4 className="py-4 text-teal-600">Tools I use</h4>
      <p className="text-gray-800 py-1">Github</p>
      <p className="text-gray-800 py-1">Vscode</p>
    </>)
  },
  {
    title: "All My Code",
    description: "Proident mollit amet aliquip dolor consequat commodo fugiat aliquip laborum adipisicing cillum occaecat eiusmod.",
    children: (<>
      <h4 className="py-4 text-teal-600">Tools I use</h4>
      <p className="text-gray-800 py-1">Github</p>
      <p className="text-gray-800 py-1">Vscode</p>
    </>)
  },
]


export default function Home() {
  const [darkMode, setDarkMode] = useState(false); // Initialize darkMode state



  return (


    <div className={darkMode ? 'dark' : ""}> {/*if darkmode is true, add dark class, if not, remove it...*/}
      <Head>
        <title>Portfolio | Tawfik </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-4 md:px-8 lg:px-16 xl:px-32 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="text-black py-10 mb-12 flex justify-between dark:text-white sticky top-0.5">
            <h1 className=" font-burtons text-xl">Tawfik</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/resume.png">Resumé</a>

              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400 ">Tawfik Ali</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-200" >I create programs utilizing python, js, java, and more!</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            {socials.map(data => (<Socials href={data.href} sourcey={data.sourcey}></Socials>))}
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden">
            <Image src={av} layout="fill" objectFit="cover" />
          </div>
        </section>


        <section>
          <div className="dark:text-white">
            <h3 classname="text-3xl py-1">All Services I illustrate</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">In Progress <span className="text-teal-500">(WIP)</span></p>
          </div>
          <div className="lg:flex gap-10 grid grid-cols-ram2"> {/*responsive web design, large screen flex and also have gap-10 */}
            {cardInfo.map(data => (<Card title={data.title} description={data.description}>{data.children}</Card>))}
          </div>
        </section>
        <section>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap" >
            <h3 className="text-3xl py-1 dark:text-white">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 dark:text-white">I've been interested in programming for a while, and have created independent projects for self-use.</p>
          </div>
          <div className="flex justify-center">
            <div className="w-full grid gap-3 grid-cols-ram" > {/* This has maximum of 3 cols per row, small screen, medium screen responsiveness as well  */}
              {portfolioInfo.map(data => (<ActivitiesCard description={data.description} sourcey={data.sourcey}></ActivitiesCard>))}
            </div>
          </div>
        </section>




        <section className="pb-5 text-center items-center ">
          <h1 className="text-5xl pb-5 dark:text-white">React Projects</h1>
          
          <div className="gap-10 grid grid-cols-ram2">
          <Suspense fallback={<div>Loading...</div> }> {/*I placed it here since wasn't loading previously, now lazy loading is working dynamically. */}
            <Project title="Calculator" description="Test" >
              <LazyCalculator />

            </Project>
          </Suspense>
          <Suspense fallback={<div>Loading...</div>}> {/*I placed it here since wasn't loading previously, now lazy loading is working dynamically. */}
            <Project title="15 Puzzle" description="Test" >
              <LazyGame/>
              
            </Project>
          </Suspense>
          </div>
        </section>
        

      </main>
    </div>
  );
}

// TO DO
/*
 * Make it a slideshow --> arrow keys that showcase each card project left and right.
 * Finish more than 2 projects that show your experience in react.
 */
